ALTER TABLE public.anuncio_visitas ADD CONSTRAINT anuncio_visitas_anuncio_id_fkey FOREIGN KEY (anuncio_id) REFERENCES public.anuncios (id) ON DELETE CASCADE;
ALTER TABLE public.anuncio_visitas ADD CONSTRAINT anuncio_visitas_visitante_id_fkey FOREIGN KEY (visitante_id) REFERENCES public.usuarios (id);
ALTER TABLE public.anuncios ADD CONSTRAINT anuncios_subrubro_id_fkey FOREIGN KEY (subrubro_id) REFERENCES public.subrubros (id);
ALTER TABLE public.anuncios ADD CONSTRAINT anuncios_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.barrios ADD CONSTRAINT barrios_ciudad_id_fkey FOREIGN KEY (ciudad_id) REFERENCES public.ciudades (id);
ALTER TABLE public.bits_promo_descargas ADD CONSTRAINT bits_promo_descargas_comprador_id_fkey FOREIGN KEY (comprador_id) REFERENCES public.usuarios (id);
ALTER TABLE public.bits_promo_descargas ADD CONSTRAINT bits_promo_descargas_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id);
ALTER TABLE public.bits_promo_descargas ADD CONSTRAINT bits_promo_descargas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.bot_mensajes ADD CONSTRAINT bot_mensajes_bot_id_fkey FOREIGN KEY (bot_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.bot_mensajes ADD CONSTRAINT bot_mensajes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.busqueda_matches ADD CONSTRAINT busqueda_matches_anuncio_id_fkey FOREIGN KEY (anuncio_id) REFERENCES public.anuncios (id) ON DELETE CASCADE;
ALTER TABLE public.busqueda_matches ADD CONSTRAINT busqueda_matches_busqueda_id_fkey FOREIGN KEY (busqueda_id) REFERENCES public.busquedas_automaticas (id) ON DELETE CASCADE;
ALTER TABLE public.busqueda_matches ADD CONSTRAINT busqueda_matches_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.busquedas_automaticas ADD CONSTRAINT busquedas_automaticas_subrubro_id_fkey FOREIGN KEY (subrubro_id) REFERENCES public.subrubros (id);
ALTER TABLE public.busquedas_automaticas ADD CONSTRAINT busquedas_automaticas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.ciudades ADD CONSTRAINT ciudades_provincia_id_fkey FOREIGN KEY (provincia_id) REFERENCES public.provincias (id);
ALTER TABLE public.comisiones_promotor ADD CONSTRAINT comisiones_promotor_origen_id_fkey FOREIGN KEY (origen_id) REFERENCES public.usuarios (id);
ALTER TABLE public.comisiones_promotor ADD CONSTRAINT comisiones_promotor_promotor_id_fkey FOREIGN KEY (promotor_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.conexiones ADD CONSTRAINT conexiones_anuncio_id_fkey FOREIGN KEY (anuncio_id) REFERENCES public.anuncios (id) ON DELETE CASCADE;
ALTER TABLE public.conexiones ADD CONSTRAINT conexiones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.conexiones ADD CONSTRAINT conexiones_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.conexiones_nexo ADD CONSTRAINT conexiones_nexo_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.conexiones_nexo ADD CONSTRAINT conexiones_nexo_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.conexiones_nexo ADD CONSTRAINT conexiones_nexo_vendedor_id_fkey FOREIGN KEY (vendedor_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.contactos_nexonet ADD CONSTRAINT contactos_nexonet_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.copyright_claims ADD CONSTRAINT copyright_claims_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.usuarios (id);
ALTER TABLE public.empresa_filtros ADD CONSTRAINT empresa_filtros_subrubro_id_fkey FOREIGN KEY (subrubro_id) REFERENCES public.empresa_subrubros (id) ON DELETE CASCADE;
ALTER TABLE public.empresa_pagos ADD CONSTRAINT empresa_pagos_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.empresa_pagos ADD CONSTRAINT empresa_pagos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.empresa_subrubros ADD CONSTRAINT empresa_subrubros_rubro_id_fkey FOREIGN KEY (rubro_id) REFERENCES public.empresa_rubros (id) ON DELETE CASCADE;
ALTER TABLE public.filtros ADD CONSTRAINT filtros_subrubro_id_fkey FOREIGN KEY (subrubro_id) REFERENCES public.subrubros (id);
ALTER TABLE public.grupo_eventos ADD CONSTRAINT grupo_eventos_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_invitaciones ADD CONSTRAINT grupo_invitaciones_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_invitaciones ADD CONSTRAINT grupo_invitaciones_invitado_id_fkey FOREIGN KEY (invitado_id) REFERENCES public.usuarios (id);
ALTER TABLE public.grupo_invitaciones ADD CONSTRAINT grupo_invitaciones_invitador_id_fkey FOREIGN KEY (invitador_id) REFERENCES public.usuarios (id);
ALTER TABLE public.grupo_mensajes ADD CONSTRAINT grupo_mensajes_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_mensajes ADD CONSTRAINT grupo_mensajes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.grupo_miembros ADD CONSTRAINT grupo_miembros_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_miembros ADD CONSTRAINT grupo_miembros_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_planos ADD CONSTRAINT grupo_planos_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_proveedores ADD CONSTRAINT grupo_proveedores_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_publicaciones ADD CONSTRAINT grupo_publicaciones_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_publicaciones ADD CONSTRAINT grupo_publicaciones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.grupo_residentes ADD CONSTRAINT grupo_residentes_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_residentes ADD CONSTRAINT grupo_residentes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.grupo_servicios ADD CONSTRAINT grupo_servicios_grupo_id_fkey FOREIGN KEY (grupo_id) REFERENCES public.grupos (id) ON DELETE CASCADE;
ALTER TABLE public.grupo_subcategorias ADD CONSTRAINT grupo_subcategorias_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.grupo_categorias (id) ON DELETE CASCADE;
ALTER TABLE public.grupos ADD CONSTRAINT grupos_categoria_id_fkey FOREIGN KEY (categoria_id) REFERENCES public.grupo_categorias (id);
ALTER TABLE public.grupos ADD CONSTRAINT grupos_creador_id_fkey FOREIGN KEY (creador_id) REFERENCES public.usuarios (id) ON DELETE SET NULL;
ALTER TABLE public.grupos ADD CONSTRAINT grupos_subcategoria_id_fkey FOREIGN KEY (subcategoria_id) REFERENCES public.grupo_subcategorias (id);
ALTER TABLE public.insignias_reputacion ADD CONSTRAINT insignias_reputacion_anuncio_id_fkey FOREIGN KEY (anuncio_id) REFERENCES public.anuncios (id);
ALTER TABLE public.insignias_reputacion ADD CONSTRAINT insignias_reputacion_dador_id_fkey FOREIGN KEY (dador_id) REFERENCES public.usuarios (id);
ALTER TABLE public.insignias_reputacion ADD CONSTRAINT insignias_reputacion_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id);
ALTER TABLE public.insignias_reputacion ADD CONSTRAINT insignias_reputacion_receptor_id_fkey FOREIGN KEY (receptor_id) REFERENCES public.usuarios (id);
ALTER TABLE public.liquidaciones_promotor ADD CONSTRAINT liquidaciones_promotor_promotor_id_fkey FOREIGN KEY (promotor_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.log_bits_internos ADD CONSTRAINT log_bits_internos_asignado_por_fkey FOREIGN KEY (asignado_por) REFERENCES public.usuarios (id);
ALTER TABLE public.log_bits_internos ADD CONSTRAINT log_bits_internos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.log_fallos_sistema ADD CONSTRAINT log_fallos_sistema_resuelto_por_fkey FOREIGN KEY (resuelto_por) REFERENCES public.usuarios (id) ON DELETE SET NULL;
ALTER TABLE public.log_fallos_sistema ADD CONSTRAINT log_fallos_sistema_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE SET NULL;
ALTER TABLE public.log_socios_comerciales ADD CONSTRAINT log_socios_comerciales_socio_id_fkey FOREIGN KEY (socio_id) REFERENCES public.socios_comerciales (id) ON DELETE CASCADE;
ALTER TABLE public.log_socios_comerciales ADD CONSTRAINT log_socios_comerciales_usuario_comprador_id_fkey FOREIGN KEY (usuario_comprador_id) REFERENCES public.usuarios (id);
ALTER TABLE public.mensajes ADD CONSTRAINT mensajes_anuncio_id_fkey FOREIGN KEY (anuncio_id) REFERENCES public.anuncios (id) ON DELETE SET NULL;
ALTER TABLE public.mensajes ADD CONSTRAINT mensajes_emisor_id_fkey FOREIGN KEY (emisor_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.mensajes ADD CONSTRAINT mensajes_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE SET NULL;
ALTER TABLE public.mensajes ADD CONSTRAINT mensajes_receptor_id_fkey FOREIGN KEY (receptor_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.mensajes_soporte ADD CONSTRAINT mensajes_soporte_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE SET NULL;
ALTER TABLE public.nexo_descarga_solicitudes ADD CONSTRAINT nexo_descarga_solicitudes_descarga_id_fkey FOREIGN KEY (descarga_id) REFERENCES public.nexo_descargas (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_descarga_solicitudes ADD CONSTRAINT nexo_descarga_solicitudes_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_descarga_solicitudes ADD CONSTRAINT nexo_descarga_solicitudes_solicitante_id_fkey FOREIGN KEY (solicitante_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_descargas ADD CONSTRAINT nexo_descargas_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.nexo_slider_items (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_descargas ADD CONSTRAINT nexo_descargas_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_descargas_pagos ADD CONSTRAINT nexo_descargas_pagos_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.usuarios (id);
ALTER TABLE public.nexo_descargas_pagos ADD CONSTRAINT nexo_descargas_pagos_comprador_id_fkey FOREIGN KEY (comprador_id) REFERENCES public.usuarios (id);
ALTER TABLE public.nexo_descargas_pagos ADD CONSTRAINT nexo_descargas_pagos_descarga_id_fkey FOREIGN KEY (descarga_id) REFERENCES public.nexo_descargas (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_descargas_pagos ADD CONSTRAINT nexo_descargas_pagos_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_flash_envios ADD CONSTRAINT nexo_flash_envios_emisor_id_fkey FOREIGN KEY (emisor_id) REFERENCES public.usuarios (id);
ALTER TABLE public.nexo_flash_envios ADD CONSTRAINT nexo_flash_envios_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_flash_envios ADD CONSTRAINT nexo_flash_envios_plantilla_id_fkey FOREIGN KEY (plantilla_id) REFERENCES public.nexo_plantillas_mensaje (id);
ALTER TABLE public.nexo_horarios ADD CONSTRAINT nexo_horarios_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_mensajes ADD CONSTRAINT nexo_mensajes_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_mensajes ADD CONSTRAINT nexo_mensajes_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_miembros ADD CONSTRAINT nexo_miembros_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_miembros ADD CONSTRAINT nexo_miembros_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_plantillas_mensaje ADD CONSTRAINT nexo_plantillas_mensaje_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_plantillas_mensaje ADD CONSTRAINT nexo_plantillas_mensaje_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.nexo_resenas ADD CONSTRAINT nexo_resenas_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_resenas ADD CONSTRAINT nexo_resenas_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.nexo_slider_anuncios ADD CONSTRAINT nexo_slider_anuncios_anuncio_id_fkey FOREIGN KEY (anuncio_id) REFERENCES public.anuncios (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_slider_anuncios ADD CONSTRAINT nexo_slider_anuncios_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_slider_anuncios ADD CONSTRAINT nexo_slider_anuncios_slider_id_fkey FOREIGN KEY (slider_id) REFERENCES public.nexo_sliders (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_slider_anuncios ADD CONSTRAINT nexo_slider_anuncios_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_slider_items ADD CONSTRAINT nexo_slider_items_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_slider_items ADD CONSTRAINT nexo_slider_items_publicado_por_fkey FOREIGN KEY (publicado_por) REFERENCES public.usuarios (id);
ALTER TABLE public.nexo_slider_items ADD CONSTRAINT nexo_slider_items_slider_id_fkey FOREIGN KEY (slider_id) REFERENCES public.nexo_sliders (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_sliders ADD CONSTRAINT nexo_sliders_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_visitas ADD CONSTRAINT nexo_visitas_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE CASCADE;
ALTER TABLE public.nexo_visitas ADD CONSTRAINT nexo_visitas_visitante_id_fkey FOREIGN KEY (visitante_id) REFERENCES public.usuarios (id);
ALTER TABLE public.nexos ADD CONSTRAINT nexos_rubro_id_fkey FOREIGN KEY (rubro_id) REFERENCES public.rubros (id);
ALTER TABLE public.nexos ADD CONSTRAINT nexos_subrubro_id_fkey FOREIGN KEY (subrubro_id) REFERENCES public.subrubros (id);
ALTER TABLE public.nexos ADD CONSTRAINT nexos_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.notificaciones ADD CONSTRAINT notificaciones_anuncio_id_fkey FOREIGN KEY (anuncio_id) REFERENCES public.anuncios (id) ON DELETE CASCADE;
ALTER TABLE public.notificaciones ADD CONSTRAINT notificaciones_emisor_id_fkey FOREIGN KEY (emisor_id) REFERENCES public.usuarios (id);
ALTER TABLE public.notificaciones ADD CONSTRAINT notificaciones_nexo_id_fkey FOREIGN KEY (nexo_id) REFERENCES public.nexos (id) ON DELETE SET NULL;
ALTER TABLE public.notificaciones ADD CONSTRAINT notificaciones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.pagos_mp ADD CONSTRAINT pagos_mp_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.push_suscripciones ADD CONSTRAINT push_suscripciones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.servicio_filtros ADD CONSTRAINT servicio_filtros_subrubro_id_fkey FOREIGN KEY (subrubro_id) REFERENCES public.servicio_subrubros (id) ON DELETE CASCADE;
ALTER TABLE public.servicio_subrubros ADD CONSTRAINT servicio_subrubros_rubro_id_fkey FOREIGN KEY (rubro_id) REFERENCES public.servicio_rubros (id) ON DELETE CASCADE;
ALTER TABLE public.sesiones_log ADD CONSTRAINT sesiones_log_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.socios_comerciales ADD CONSTRAINT socios_comerciales_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.solicitudes_reembolso_promotor ADD CONSTRAINT solicitudes_reembolso_promotor_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.subrubro_filtros ADD CONSTRAINT subrubro_filtros_subrubro_id_fkey FOREIGN KEY (subrubro_id) REFERENCES public.subrubros (id) ON DELETE CASCADE;
ALTER TABLE public.subrubros ADD CONSTRAINT subrubros_rubro_id_fkey FOREIGN KEY (rubro_id) REFERENCES public.rubros (id);
ALTER TABLE public.sugerencias_categorias ADD CONSTRAINT sugerencias_categorias_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id);
ALTER TABLE public.suscripciones_mp ADD CONSTRAINT suscripciones_mp_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.trabajo_filtros ADD CONSTRAINT trabajo_filtros_subrubro_id_fkey FOREIGN KEY (subrubro_id) REFERENCES public.trabajo_subrubros (id) ON DELETE CASCADE;
ALTER TABLE public.trabajo_subrubros ADD CONSTRAINT trabajo_subrubros_rubro_id_fkey FOREIGN KEY (rubro_id) REFERENCES public.trabajo_rubros (id) ON DELETE CASCADE;
ALTER TABLE public.usuarios ADD CONSTRAINT usuarios_referido_por_fkey FOREIGN KEY (referido_por) REFERENCES public.usuarios (id);
ALTER TABLE public.usuarios ADD CONSTRAINT usuarios_socio_regional_id_fkey FOREIGN KEY (socio_regional_id) REFERENCES public.socios_comerciales (id);
ALTER TABLE public.usuarios_conectados ADD CONSTRAINT usuarios_conectados_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
ALTER TABLE public.usuarios_mp_tokens ADD CONSTRAINT usuarios_mp_tokens_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES public.usuarios (id) ON DELETE CASCADE;
